---
apiVersion: v1
kind: Service
metadata:
  name: friendbot-futurenet
  namespace: sandbox
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80         # port number the service will listen on
    targetPort: 8004 # # port number pods listen on
  selector:
    app: friendbot-futurenet
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: friendbot-futurenet
  namespace: friendbot-prd
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "default"
spec:
  tls:
  - secretName: friendbot-futurenet-cert
    hosts:
    - friendbot #### ???
  rules:
  - host: friendbot #### ???
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: friendbot-futurenet
            port:
              number: 80
