---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- else }}
  namespace: sandbox
  {{- end }}
  labels:
    app: {{ template "common.fullname" . }}
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.friendbot.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "common.fullname" . }}
  strategy:
    type: RollingUpdate
    maxUnavailable: 0
    maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ template "common.fullname" . }}
        release: {{ .Release.Name }}
      {{- if (.Values.friendbot.deployment).labels }}
        {{- range $key, $value := .Values.friendbot.deployment.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      {{- if (.Values.friendbot.deployment).annotations }}
      annotations:
        {{- range $key, $value := .Values.friendbot.deployment.annotations }}
          {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      {{- if (.Values.friendbot).serviceAccountName }}
      serviceAccountName: {{ .Values.friendbot.serviceAccountName | default "default" }}
      {{- end }}
      containers:
      - name: friendbot
        image: {{ include "common.friendbotImage" . | quote }}
        {{- if (.Values.friendbot).cliArgs }}
        args:
          {{- range $flag := .Values.friendbot.cliArgs }}
          - {{ $flag | quote }}
          {{- end }}
        {{- end }}
        imagePullPolicy: {{ .Values.global.image.friendbot.pullPolicy }}
        startupProbe:
          tcpSocket: {{ .Values.friendbot.friendbotConfig.adminPort | default 6000 }}
          initialDelaySeconds: {{ }}
          failureThreshold: {{ }}
          periodSeconds: {{ }}
          timeoutSeconds: {{ }}
        envFrom:
        - secretRef:
            name: {{ .Values.friendbot.existingSecret }}
        - configMapRef:
            name: {{ template "common.fullname" . }}-env
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: {{ template "common.fullname" . }}
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.friendbot.service.port | default 80 }}
    targetPort: {{ .Values.friendbot.service.targetport | default 8004 }}
  selector:
    app: {{ template "common.fullname" . }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "common.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  annotations:
    {{- range $key, $value := .Values.friendbot.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
  - secretName: friendbot-futurenet-cert
    hosts:
    - {{ .Values.friendbot.ingress.host }}
  rules:
  - host: {{ .Values.friendbot.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "common.fullname" . }}
            port:
              number: {{ .Values.friendbot.ingress.port | default 80 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.fullname" . }}-env
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: {{ template "common.fullname" . }}
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  port = {{ .Values.friendbot.configmap.port | default 8000 }}
  friendbot_secret = {{ .Values.friendbot.configmap }}
  network_passphrase =  {{ .Values.global.network_passphrase }}
  horizon_url =  {{ .Values.global.horizon_url }}
  starting_balance =  {{ .Values.friendbot.configmap.starting_balance | default 10000 }}
  num_minions = {{ .Values.friendbot.configmap.num_minions | default 1000 }}
  base_fee = {{ .Values.friendbot.configmap.base_fee | default 100000 }}
  minion_batch_size = {{ .Values.friendbot.configmap.minion_batch_size | default 50 }}
  submit_tx_retries_allowed = {{ .Values.friendbot.configmap.tx | default 5 }

