apiVersion: v1
name: friendbot
description: This chart will deploy friendbot to your private network
version: 0.0.1
appVersion: "6fbbdc47"
description: Stellar Friendbot Helm Chart
maintainers: 
  - name: Stellar Development Foundation
sources:
  - https://github.com/stellar/helm-charts
