global:
  # namespace: mynamespace
  network: futurenet
  network_passphrase: "My Stellar Network 2022"
  horizon_url: "https://horizon-testnet.stellar.org"
  # nameOverride:
  # fullnameOverride:

  image:
    friendbot:
      registry: docker-registry.services.stellar-ops.com
      repository: dev/
      ## Optional tag. Defaults to the appVersion from Chart.yaml
      # tag: x.x.x

      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      pullPolicy: IfNotPresent

friendbot:

  cliArgs:
  - "--conf /config/friendbot.conf"
  replicaCount: 1

  # serviceAccountName: default

  deployment:
    # annotations:
    #   prometheus.io/scrape: "true"
    #   prometheus.io/port: "6000"
    # labels:
    #   environment: "dev"
    #   mylabel1: "myvalue1"

  service:
    port: 80
    targetport: 8004

  ingress:
    # port: 80
    annotations:
      kubernetes.io/ingress.class: "private"
      cert-manager.io/cluster-issuer: "default"
    host: "friendbot.example.com"

  configmap:
    port: 8000 
    friendbot_secret: "XXXXXXX"
    # starting_balance: 10000
    # num_minions: 1000
    # base_fee: 10000
    # minion_batch_size: 50
    # submit_tx_retries_allowed: 5

