global:
  ## String to use to explicitly set namespace name in manifests.
  ## Useful for those using "helm template" to render templates
  # namespace: mynamespace

  ## String to partially override common.fullname template (will maintain the release name)
  ##
  # nameOverride:

  ## String to fully override common.fullname template
  ##
  # fullnameOverride:

  ## List of pre-existing image Pull Secrets to use
  # imagePullSecrets:
  # - imagepullsecret1
  # - imagepullsecret2

  image:
    sorobanRpc:
      registry: docker.io
      repository: stellar/soroban-rpc
      ## Optional tag. Defaults to the appVersion from Chart.yaml
      # tag: abc123

      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: Always

sorobanRpc:
  ## See global.image.sorobanRpc for image settings


  ## This variable allows overrides of default settings. It will be used as a container port
  ## and port where soroban-rpc server will listen.
  # port: 8000

  ## Soroban-rpc config variables
  sorobanRpcConfig:
    endopoint: "0.0.0.0:8000"
    friendbotUrl: "https://friendbot-futurenet.stellar.org/"
    networkPassphrase: "Test SDF Future Network ; October 2022"
    stellarCoreUrl: "http://localhost:11626"
    historyArchiveUrls: "http://history-futurenet.stellar.org"
    dbPath: "/var/lib/stellar/soroban-rpc-db.sqlite"
    stellarCaptiveCorePort: 11626
    checkpointFrequence: 64

  coreConfig:
    networkPassphrase: "Test SDF Future Network ; October 2022"
    httpPort: 11626
    publicHttpPort: true
    peerPort: 11625

    database: "sqlite3:///var/lib/stellar/stellar-captive-core.db"
    bucketlistDb: "true"
    bucketlistDbIndexPageSizeExponent: 12

    failureSafety: 0
    unsafeQuorum: true

    homeDomains:
    - homeDomain: "futurenet.stellar.org"
      quality: "MEDIUM"
    validators:
      - name: "sdf_futurenet_1"
        homeDomain: "futurenet.stellar.org"
        publicKey: "GBRIF2N52GVN3EXBBICD5F4L5VUFXK6S6VOUCF6T2DWPLOLGWEPPYZTF"
        address: "horizon-devnet-core-001a.dev.stellar002.external.stellar-ops.com"
        history: "curl -sf http://history-futurenet.stellar.org/{0} -o {1}"
      - name: "sdf_futurenet_2"
        homeDomain: "futurenet.stellar.org"
        publicKey: "GAQM2MF22BYOGIF47RZ2523YK7ZL7Z3CIIX6CCPZBWWLE6KJTXMD4SLO"
        address: "horizon-devnet-core-002a.dev.stellar002.external.stellar-ops.com"
        history: "curl -sf http://history-futurenet.stellar.org/{0} -o {1}"
      - name: "sdf_futurenet_3"
        homeDomain: "futurenet.stellar.org"
        publicKey: "GC2HLBHG4Z7KV73OPKZD6EWXIXM5QOIZVKN5OS4V2HISDOJC3TUORLY4"
        address: "horizon-devnet-core-003a.dev.stellar002.external.stellar-ops.com"
        history: "curl -sf http://history-futurenet.stellar.org/{0} -o {1}"

  ingress:
    host: example.com
    annotations:
      kubernetes.io/ingress.class: "public"
      cert-manager.io/cluster-issuer: "default"

  ## Whether to provision persistent volume. Recommended for production use cases
  persistence:
    enabled: false
    storageClass: default
    size: 100G

  ## Uncomment to use custom service account
  # serviceAccountName: default

  ## Additional annotations or labels to add the StatefulSet template
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "8001"
  # labels:
  #   environment: "dev"
  #   mylabel1: "dev-value"

  ## Uncomment to set resource limits
  # resources:
  #  limits:
  #    cpu: 2
  #    memory: 4Gi
  #  requests:
  #    cpu: 250m
  #    memory: 2Gi

