apiVersion: v1
name: stellar-network
description: This chart will deploy a Stellar network to Kubernetes
version: 0.0.1
description: Stellar Network Helm Chart
maintainers: 
  - name: Stellar Development Foundation
sources:
  - https://github.com/stellar/helm-charts
dependencies:
  - name: core
    repository: "https://helm.stellar.org/charts"
    version: 0.0.1
    condition: core.enabled
  - name: horizon
    repository: "https://helm.stellar.org/charts"
    version: 0.0.3
    condition: horizon.enabled
  - name: soroban-rpc
    repository: "https://helm.stellar.org/charts"
    version: 0.0.1
    condition: soroban-rpc.enabled
  - name: friendbot
    repository: "https://helm.stellar.org/charts"
    version: 0.0.1
    condition: friendbot.enabled
